spring:
  thymeleaf:
    prefix: classpath:/template/
    cache: true
    reactive:
      max-chunk-size: 8192
  r2dbc:
       url: r2dbc:pool:postgresql://localhost:5432/spring
       username: spring
       password: 1234
       
  data:
    r2dbc:
      repositories:
        enabled: true
logging:
  level:
    org:
      springframework:
        web: INFO